### PR TITLE
Adds functionality for game version selection

### PR DESCRIPTION
**Pull request by LucMellee**
I've added the ability to change the game version. The dropdown menu is resized to fit the largest item in the list.
In addition to having the ability to select a game version the pack_format will also be set accordingly. Pack formats can be added and removed in packformats.py

### CODE REVIEW

**Comment by bradytheinventor** [comment]
This is helpful and a great first step towards supporting multiple versions. Unfortunately, this problem is bigger than just updating `pack_format`. In 1.17, the `/replaceitem` command was changed to `/item replace`, which required me to change the datapack code. So switching versions may also change the datapack a little, and this changing should ideally be extendable, in case more commands change in the future. I haven't decided how to implement this in a way that doesn't involve scattering ifs throughout the code or duplicating large chunks of functions.

On top of that, I've had a soft goal of keeping `generator.py` self-contained, so it can eventually be turned into a standalone command-line version of the tool. That can pick up the cross-platform slack until I get around to making Mac and Linux versions of the app.

So... this is actually a rather complicated feature. You seem to know Python well; I would love to hear if these goals sound sensible and Pythonic, or just kinda weird.

**Comment by LucMellee** [comment]
Hi!

About creating a standalone console application, I think it doesn't really matter that there are additional python files. You can easily ship them with your generator script. However, in order to replace the components and definitions file you might need to change a few fundamental elements of generator.py.

First off, in order to go console you need to allow the user to configure the user settings through the use of call parameters. Next you need to create an interactive environment in which the user could select their tracks and set their names. Once they confirm their selection you can go about generating the data pack the way you've been doing it now.

As for the version changing. I had not thought about commands changing in different Minecraft versions. I'll try to come up with some modular system that allows you easily configure different commands. Ideally I find a way to do this without having to change all that much about the current code structure in the generatot, but I'm going to have to tinker with it for a bit.

I'll keep you updated!

**Comment by LucMellee** [comment]
Alright, I've come up with a system that allows the creation of different commands for different game versions. Here I have an example for just the `replaceitem` command. I've also tested code by implementing it directly into the generator and it appears to work.

**Comment by bradytheinventor** [comment]
I like your approach to building commands with different variants. It's clean, pretty extendable, and matches the coding style of the project.

Looking over your `pack_format` code again, I think I can use dictionaries to reduce the overhead (fewer functions, no json parsing). If you're ok with that, I can merge this pull request and make changes on my side, do bug testing, etc.

**Comment by LucMellee** [comment]
That is totally okay with me! Just glad I could help :)

**Pull request merged**
